# Generated by Django 5.2.5 on 2025-08-18 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя животного')),
                ('species', models.CharField(max_length=50, verbose_name='Вид (например, собака, кошка)')),
                ('breed', models.CharField(blank=True, max_length=50, verbose_name='Порода')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/photos/', verbose_name='Фотография')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_services', to='main.animal', verbose_name='Животное')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, verbose_name='Родословная')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='main.animal', verbose_name='Животное')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вакцины')),
                ('date', models.DateField(verbose_name='Дата вакцинации')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='main.animal', verbose_name='Животное')),
            ],
        ),
    ]
