# Generated by Django 5.1.2 on 2025-10-21 10:49

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (URL)')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/previews/', verbose_name='Превью-изображение')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Текст статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='main.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Демонстрационная клиника')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кабинета клиники')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', '₽ Российский рубль'), ('USD', '$ Доллар США'), ('EUR', '€ Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность по умолчанию, мин')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_services', to='main.clinic', verbose_name='Клиника')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_services', to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга клиники',
                'verbose_name_plural': 'Услуги клиники',
                'ordering': ['sort_order', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='AnimalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_service_name', models.CharField(blank=True, max_length=100, verbose_name='Своя услуга (название)')),
                ('service_description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время услуги')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость')),
                ('custom_description', models.TextField(blank=True, verbose_name='Комментарий/детали (необязательно)')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Кастомная услуга (только для этого пользователя)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to='main.animal', verbose_name='Животное')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_services_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_services', to='main.clinic', verbose_name='Клиника')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Вид услуги')),
            ],
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО врача')),
                ('specialties', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='Био')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vets', to='main.clinic', verbose_name='Клиника')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-врач')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='VetAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало (локальное время клиники)')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Окончание (локальное время клиники)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Конкретная дата (локальная)')),
                ('slot_minutes', models.PositiveIntegerField(default=30, verbose_name='Длительность слота, мин')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.clinic', verbose_name='Клиника')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.vetprofile', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Окно доступности врача',
                'verbose_name_plural': 'Окна доступности врачей',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Окончание')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('cancelled', 'Отменена'), ('completed', 'Завершена'), ('rescheduled', 'Перенесена')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='main.animal', verbose_name='Животное')),
                ('booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_booked', to=settings.AUTH_USER_MODEL, verbose_name='Кто записал')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='main.clinic', verbose_name='Клиника')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='main.vetprofile', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_at'],
            },
        ),
        migrations.DeleteModel(
            name='MedicalService',
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['clinic', 'is_active'], name='main_clinic_clinic__79ca5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicservice',
            unique_together={('clinic', 'service')},
        ),
        migrations.AddIndex(
            model_name='vetavailability',
            index=models.Index(fields=['clinic', 'vet', 'is_active'], name='main_vetava_clinic__fa22b0_idx'),
        ),
        migrations.AddIndex(
            model_name='vetavailability',
            index=models.Index(fields=['weekday'], name='main_vetava_weekday_547e28_idx'),
        ),
        migrations.AddIndex(
            model_name='vetavailability',
            index=models.Index(fields=['date'], name='main_vetava_date_e9a9f2_idx'),
        ),
    ]
