"""
Django settings for medanit project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer env variable in production
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-t^$78*^f+dcs$iky=e%w*_ktpvj0!9p-kc&6k+tz0zjs2y81%-'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #os.getenv('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

# Hosts and CSRF
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*.pythonanywhere.com,localhost,127.0.0.1').split(',')

# If you expose the site on a domain, add it here to allow secure POSTs (e.g., Cal.com webhooks via HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://*.pythonanywhere.com',
    'https://*.ngrok-free.app',  # if you test webhooks via ngrok
    # 'https://your-domain.ru',  # add your real domain(s) here
]

# Authentication redirects
LOGIN_REDIRECT_URL = 'animals/'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'main',

    # Third-party apps
    'ckeditor',          # requires: pip install django-ckeditor
    'widget_tweaks',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medanit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # optional: use a project-level templates dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medanit.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Sessions
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
# Where collectstatic will put files (important for PythonAnywhere)
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Optionally, if you have a /static directory with custom assets (CSS/JS)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------- Cal.com integration settings --------
# Secret for verifying webhook signatures
CAL_SIGNING_SECRET = os.getenv('CAL_SIGNING_SECRET', '')
# Base URL for Cal.com (change if you use self-hosted Cal)
CAL_BASE_URL = os.getenv('CAL_BASE_URL', 'https://cal.com')

# -------- CKEditor basic config (optional) --------
# If you use upload features, configure storage and upload path
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = os.getenv('CKEDITOR_IMAGE_BACKEND', '')  # e.g., "pillow"
# Example minimal toolbar (you can customize as needed)
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Basic',
        'height': 200,
        'width': 'auto',
    }
}

# -------- Logging (webhook debug etc.) --------
LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '[{levelname}] {asctime} {name}: {message}', 'style': '{'},
        'simple': {'format': '[{levelname}] {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        }
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Your apps
        'main': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
        # Django request warnings etc.
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': True},
    },
}